[package]
name = "libtapasco_svm"
version = "1.0.0"
authors = ["Torben Kalkhof <kalkhof@esa.tu-darmstadt.de>"]
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[dependencies]
tapasco = { path = "../../../libtapasco" }
snafu = "0.7.0"
log = "0.4.14"
env_logger = "0.9.0"
